version: "3.1"

services:

  drupal:
    image: drupal:10-php8.3-apache
    ports:
      - 8080:80
    volumes:
#      - /var/www/html/drupal/modules
#      - /var/www/html/drupal/profiles
#      - /var/www/html/drupal/themes
#      - /var/www/html/sites
      - .:/opt/drupal
    environment:
      - DRUPAL_DB_HOST=db
      - DRUPAL_DB_NAME=drupal
      - DRUPAL_DB_USER=drupal
      - DRUPAL_DB_PASSWORD=drupal
    networks:
      - net
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8.0.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - net
    restart: always

volumes:
  db-data:

networks:
  net:
    driver: bridge
